### ISSUE TITLE
System.MethodAccessException in NET47

### ISSUE THREAD

**Issue by hype8912** [tonerdo/pose#2] opened 2017-10-13 02:30 UTC
Using Pose NuGet Package 1.0.0 with XUnit 2.2.0 in .NET 4.7.
Get the following error trying to execute the test method.

Test Name:	GetInformationalVersionTest_CurrentAssembly_NullAttribute
Test FullName:	Bigcomp.Tests.Reflection.ReflectionExtensionsTests.GetInformationalVersionTest_CurrentAssembly_NullAttribute
Test Outcome:	Failed
Test Duration:	0:00:00.303

Result StackTrace:	at dynamic_Bigcomp.Tests.Reflection.ReflectionExtensionsTests+<>c_<GetInformationalVersionTest_CurrentAssembly_NullAttribute>b__2_1(<>c )
Result Message:	System.MethodAccessException : Attempt by method 'DynamicClass.dynamic_Bigcomp.Tests.Reflection.ReflectionExtensionsTests+<>c_<GetInformationalVersionTest_CurrentAssembly_NullAttribute>b__2_1(<>c)' to access method 'DynamicClass.dynamic_Bigcomp.Tests.Reflection.ReflectionExtensionsTests+<>c_<GetInformationalVersionTest_CurrentAssembly_NullAttribute>b__2_1(<>c)' failed.

```
       [Fact]
        public void GetInformationalVersionTest_CurrentAssembly_NullAttribute()
        {
            Shim attShim = Shim.Replace(() => Attribute.GetCustomAttribute(Is.A<Assembly>(), Is.A<Type>()))
                .With<Assembly, Type, Attribute>(
                    (assy, t) =>
                    {
                        Attribute item = null;
                        return item;
                    });

            PoseContext.Isolate(
                () =>
                {
                    Assembly assy = Assembly.GetExecutingAssembly();
                    var att =
                        Attribute.GetCustomAttribute(assy, typeof(AssemblyInformationalVersionAttribute)) as
                            AssemblyInformationalVersionAttribute;
                    string result = att?.InformationalVersion;

                    Assert.Null(result);
                }, attShim);
        }
```

**Comment by tjrobinson** [comment] 2017-10-13 08:04
This looks like a duplicate of https://github.com/tonerdo/pose/issues/1

**Comment by tonerdo** [comment] 2017-10-18 00:34
@hype8912 This issue has been fixed. Will merge into master and create a new release later today

**Closed** 2017-10-18 09:12 UTC
Labels: exception
